// <auto-generated />
using System;
using DealerPortal.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DealerPortal.Api.Data.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20260928115326_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("portal")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DealerPortal.Api.Data.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_id");

                    b.HasKey("Id")
                        .HasName("pk_app_users");

                    b.HasIndex("DealerId")
                        .HasDatabaseName("ix_app_users_dealer_id");

                    b.HasIndex("ObjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_object_id");

                    b.ToTable("app_users", "portal");
                });

            modelBuilder.Entity("DealerPortal.Api.Data.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_claims");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_claims_unit_id");

                    b.ToTable("claims", "portal");
                });

            modelBuilder.Entity("DealerPortal.Api.Data.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_dealers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_dealers_code");

                    b.ToTable("dealers", "portal");
                });

            modelBuilder.Entity("DealerPortal.Api.Data.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<DateOnly>("PublishedOn")
                        .HasColumnType("date")
                        .HasColumnName("published_on");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.ToTable("documents", "portal");
                });

            modelBuilder.Entity("DealerPortal.Api.Data.Part", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Sku")
                        .HasName("pk_parts");

                    b.ToTable("parts", "portal");
                });

            modelBuilder.Entity("DealerPortal.Api.Data.PartsOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_parts_orders");

                    b.ToTable("parts_orders", "portal");
                });

            modelBuilder.Entity("DealerPortal.Api.Data.PartsOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PartsOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("parts_order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_parts_order_lines");

                    b.HasIndex("PartsOrderId")
                        .HasDatabaseName("ix_parts_order_lines_parts_order_id");

                    b.ToTable("parts_order_lines", "portal");
                });

            modelBuilder.Entity("DealerPortal.Api.Data.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vin");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("DealerId")
                        .HasDatabaseName("ix_units_dealer_id");

                    b.HasIndex("Vin")
                        .IsUnique()
                        .HasDatabaseName("ix_units_vin");

                    b.ToTable("units", "portal");
                });

            modelBuilder.Entity("DealerPortal.Api.Data.AppUser", b =>
                {
                    b.HasOne("DealerPortal.Api.Data.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .HasConstraintName("fk_app_users_dealers_dealer_id");

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("DealerPortal.Api.Data.Claim", b =>
                {
                    b.HasOne("DealerPortal.Api.Data.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_claims_units_unit_id");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("DealerPortal.Api.Data.PartsOrderLine", b =>
                {
                    b.HasOne("DealerPortal.Api.Data.PartsOrder", null)
                        .WithMany("Lines")
                        .HasForeignKey("PartsOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parts_order_lines_parts_orders_parts_order_id");
                });

            modelBuilder.Entity("DealerPortal.Api.Data.Unit", b =>
                {
                    b.HasOne("DealerPortal.Api.Data.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_units_dealers_dealer_id");

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("DealerPortal.Api.Data.PartsOrder", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
